;
; ArthimeticandBooleanexp.asm
;
; Created: 02-02-2023 07:46:14
; Author : Admin
;


; Replace with your application code
			.EQU HEX_NUM = 0X315
			.EQU RMND_L = 0X322
			.EQU RMND_M = 0X323
			.EQU RMND_H = 0X324
			.DEF NUM = R16
			.DEF DENOMINATOR = R17
			.DEF QUOTIENT = R18
			.include "m32def.inc"
			.org 00
			LDI R21, 0XF5
			LDI R22, 0X0B
			ADC R21,R22
			LDI R26, 0X62
			LDI R27, 0X27
			LDI R28,0X96
			LDI R29,0X12
			SUB R26, R28
			SBC R27,R29
			LDI R23, 0X25
			LDI R24,0X65
			MUL R23,R24
;;;NO DIVISION MNEMONIC SO USE THIS PROGRAM;;;;
			LDI NUM, 95
			LDI DENOMINATOR, 10
			CLR QUOTIENT
	L1:		INC QUOTIENT
			SUB NUM,DENOMINATOR
			BRCC L1					; BRANCH IF C IS ZERO

			DEC QUOTIENT
			ADD NUM, DENOMINATOR
			LDI R16,0
			LDI R17,0
			LDI R18,0
;;;;;PROGRAM FOR DATA FROM SENSOR AND CONVERTIT TO DECIMAL AND SAVE LEAST SIGNIFICANT BIT IN LOCATION 0X322
			LDI R25, 0XFD		;$FD = 253 IN DECIMAL
			STS HEX_NUM,R25		;STORE $FD IN LOCATION 0X315

;;;==============================================================
			LDS NUM, HEX_NUM
			LDI DENOMINATOR ,10		;DENOMINATOR = 10

L2:			INC QUOTIENT			;
			SUB NUM, DENOMINATOR 
			BRCC L2
			DEC QUOTIENT			;ONCE TOO MANY
			ADD NUM, DENOMINATOR	;ADD BACK TO IT
			STS RMND_L, NUM

			MOV NUM, QUOTIENT
			LDI QUOTIENT,0

L3:			INC QUOTIENT
			SUB NUM, DENOMINATOR
			BRCC L3

			DEC QUOTIENT
			ADD NUM,DENOMINATOR
			STS RMND_M, NUM

			STS RMND_H, QUOTIENT

	HERE:	RJMP HERE